### PR TITLE
Create zh_CN file

### PR DESCRIPTION
**Pull request by TartaricAcid**
It seems that your GitHub repository has not yet been updated, so I was
translate it based on version 0.205

### CODE REVIEW

**Comment by elucent** [comment]
That's pretty up-to-date. I'll update with a few new things fairly soon, but that's covering most of what's in the mod! Thanks!

**Comment by TartaricAcid** [comment]
Will you update the 1.10.2 version？I have a language file that correspond to version 1.10.2.

**Comment by elucent** [comment]
The 1.10.2 version is no longer supported. If even FTB is realizing that 1.11.2 is the future of the modding community, then I see no reason to make backwards progress.

**Comment by TartaricAcid** [comment]
Thank you

**Pull request merged**
